riscv-dv: Makefile: Fail early
First commands in pipes used in `compile.log` and `iss_sim.log` targets
could previously silently fail due to `tee` command's successful exit
code.

Exit codes of these commands could be explicitly checked using
`${PIPESTATUS[0]}` but it would still require setting `SHELL` to bash
cause by default `sh` is used which doesn't support that variable. So
let's better just use bash with `pipefail` set for the current and any
future pipes.

diff --git a/tools/riscv-dv/Makefile b/tools/riscv-dv/Makefile
--- a/tools/riscv-dv/Makefile
+++ b/tools/riscv-dv/Makefile
@@ -1,3 +1,5 @@
+SHELL           = /bin/bash -o pipefail
+
 GCC_PREFIX     ?= riscv64-unknown-elf
 
 RISCV_DV_PATH   = $(RV_ROOT)/third_party/riscv-dv
@@ -148,6 +150,10 @@ $(TEST_DIR)/iss_sim.log: $(TEST_DIR)/compile.log | $(TEST_DIR)
 	# Compile, simulate
 	PYTHONPATH=$(RISCV_DV_PATH)/pygen python3 $(RISCV_DV_PATH)/run.py $(RISCV_DV_ARGS) $(RISCV_DV_SIM_ARGS) \
     --steps iss_sim 2>&1 | tee $@
+	if grep -q ERROR $(TEST_DIR)/iss_sim.log; then \
+		echo "ISS simulation failed"; \
+		exit 1; \
+	fi
 
 # Tests are built by `run.py` script, they shouldn't be constructed by this Makefile directly
 %.o:
